### ISSUE TITLE
go-metrics dependency requires dep override

### ISSUE THREAD

**Issue by bmoylan** [palantir/pkg#147]
In #142 we switched to a fork of go-metrics; in most cases this requires consuming projects to include a dep override of the form

```toml
[[override]]
  name = "github.com/rcrowley/go-metrics"
  source = "github.com/ashrayjain/go-metrics"
  branch = "aj/rescale-on-reads"
```

Ideally we would not need overrides in consuming projects
